name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: $cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            $cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn lint
  build-doc:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup caching
        uses: actions/cache@v3
        with:
          path: node_modules
          key: $cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            $cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Build doc
        run: |
          yarn doc
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apidoc
